@@ -1,31 +1,19 @@
/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:createNewRestaurant:739948:
  appc.background(230);
} //_CODE_:createNewRestaurant:739948:

public void RestaurantNameTextBox(GTextField source, GEvent event) { //_CODE_:RestaurantName:893966:
  println("RestaurantName - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:RestaurantName:893966:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:847766:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:847766:



// Create all the GUI controls. 

@@ -35,56 +23,7 @@ public void createGUI(){
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  createNewRestaurant = GWindow.getWindow(this, "Create Restaurant", 0, 0, 300, 240, JAVA2D);
  createNewRestaurant.noLoop();
  createNewRestaurant.setActionOnClose(G4P.KEEP_OPEN);
  createNewRestaurant.addDrawHandler(this, "win_draw1");
  Heading = new GLabel(createNewRestaurant, 66, 8, 120, 20);
  Heading.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Heading.setText("Create Restaurant");
  Heading.setOpaque(true);
  restaurantNameLabel = new GLabel(createNewRestaurant, 5, 40, 120, 20);
  restaurantNameLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  restaurantNameLabel.setText("Restaurant Name:");
  restaurantNameLabel.setOpaque(false);
  restaurantLocationLabel = new GLabel(createNewRestaurant, 5, 65, 120, 20);
  restaurantLocationLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  restaurantLocationLabel.setText("Restaurant Location:");
  restaurantLocationLabel.setOpaque(false);
  label1 = new GLabel(createNewRestaurant, 5, 90, 120, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Location Options:");
  label1.setOpaque(false);
  torontoLabel = new GLabel(createNewRestaurant, 5, 130, 120, 20);
  torontoLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  torontoLabel.setText("Downtown Toronto");
  torontoLabel.setOpaque(false);
  waterlooLabel = new GLabel(createNewRestaurant, 5, 160, 80, 20);
  waterlooLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  waterlooLabel.setText("Waterloo");
  waterlooLabel.setOpaque(false);
  eloraLabel = new GLabel(createNewRestaurant, 6, 190, 80, 20);
  eloraLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  eloraLabel.setText("Elora");
  eloraLabel.setOpaque(false);
  RestaurantName = new GTextField(createNewRestaurant, 135, 40, 120, 20, G4P.SCROLLBARS_NONE);
  RestaurantName.setOpaque(true);
  RestaurantName.addEventHandler(this, "RestaurantNameTextBox");
  dropList1 = new GDropList(createNewRestaurant, 136, 66, 120, 80, 3, 10);
  dropList1.setItems(loadStrings("list_847766"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  createNewRestaurant.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow createNewRestaurant;
GLabel Heading; 
GLabel restaurantNameLabel; 
GLabel restaurantLocationLabel; 
GLabel label1; 
GLabel torontoLabel; 
GLabel waterlooLabel; 
GLabel eloraLabel; 
GTextField RestaurantName; 
GDropList dropList1; 
